apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-05-09T21:40:55Z"
  name: carol1
  namespace: prometheus
  resourceVersion: "561257"
  uid: c0576649-b816-4c51-b364-197e588cb861
